version: 1
formatters:
  simple:
    format: '%(asctime)s - %(module)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S.%03d%z'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  botocore:
    level: ERROR
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]