version: 1
formatters:
  simple:
    format: "{asctime} {msecs:>03.0f} - {module} {levelname:8s} {message}"
    converter: gmtime
    style: "{"
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  botocore:
    level: ERROR
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]